from flask import Flask, render_template, Response
import cv2

# Create Flask application object
app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html')


def generate_frames():
    # Initialize camera object to capture frames from the default web camera (index 0)
    camera = cv2.VideoCapture(0)

    while True:
        # Read frame from the camera
        success, frame = camera.read()

        # If frame reading is not successful, exit the loop
        if not success:
            break
        else:
            # Encode the frame as a JPEG image
            ret, buffer = cv2.imencode('.jpg', frame)
            # Convert the encoded frame to bytes
            frame = buffer.tobytes()
            # Yield the frame as part of the multipart data
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

    # Release the camera resource
    camera.release()


@app.route('/video_feed')
def video_feed():
    # Return a response object containing the frames generated by the generate_frames() function
    return Response(generate_frames(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


if __name__ == '__main__':
    # Run the Flask application in debug mode
    app.run(debug=True)
